spring:
  datasource:
    url: jdbc:mysql://mysql-local:3306/local_db
    username: local
    password: local
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
