spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://www.ampnotice.kr/login/oauth2/code/google"

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ${S3_REGION:ap-northeast-2}
      stack:
        auto: false

app:
  oauth2:
    redirect-uri:
      audience: https://www.ampnotice.kr/auth/callback
      organizer: https://organizer.ampnotice.kr/auth/callback
    onboarding-uri:
      audience: https://www.ampnotice.kr/onboarding
      organizer: https://organizer.ampnotice.kr/onboarding
    failure-redirect-uri: https://www.ampnotice.kr/login

  cors:
    allowed-origins: >
      https://www.ampnotice.kr,
      https://ampnotice.kr,
      http://www.ampnotice.kr,
      http://ampnotice.kr,
      https://organizer.ampnotice.kr,
      http://organizer.ampnotice.kr
      http://localhost:5173,
      http://localhost:5174
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  server-url: https://www.ampnotice.kr

server:
  port: 8080

logging:
  level:
    root: INFO
    com.amp: INFO
    org.springframework.security: INFO
